[package]
name = "ragequiet"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
cpal = "0.18.2"
futures = "0.3.34"
iced = { version = "0.14.0", default-features = false, features = ["canvas", "tokio", "tiny-skia"] }
png = "0.18.1"
realfft = "3.5.0"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
symphonia = { version = "0.6.1", default-features = false, features = ["wav", "pcm", "mp3"] }
toml = "1.1.4"
tray-icon = "0.24.2"

[profile.release]
lto = "thin"
strip = true

[build-dependencies]
winresource = "0.1.31"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Graphics_Dwm", "Win32_System_SystemInformation"] }
